package com.annabee.markvshaney

import com.annabee.markvshaney.markovchain.SongLyricsMarkovChainGenerator

object MarkVShaneyApp extends App {

  val a = "Ignite the fire of all creation\ncauterize the loins from which it bears\npraise the birth of disintegration\nthe decaying of our embers flare\nInto the pits where we must fall\nthe trying fires will consume us all\nconfined, convicted, condemned to burn\nradiant be the path of no return\nOur own temple will turn to ash\nsupernova searing the souls of man\nsudden strikes with light & flash\nsmoldering stone walls now crumble like sand\nInto the pits where we must fall\nthe trying fires will consume us all\nconfined, convicted, condemned to burn\nradiant be the path of no return\nWe are but ashes in the earn\naccommodating the gift of fire\nfor no boulder will go unturned\nscorched earth funeral pyre\nLet us kindle those who observe\nlighting up the next of flesh\nblistering down to our last nerve\nbidding farewell in its final caress"
  val b = "Snakes, the great deceivers,\ngoverning the minds of man\nTrue falsifiers, coiling\n& constricting their master plan\nLeeches, cheats & liars\ninfecting the deepest drinking pools\nPure poison in the mire\nwhere we squirm like worms and defenseless fools.\nSnakes and vultures\n...you are…\nfucking snakes and vultures\n...you are…\nVultures, the sinister soars\nwith talons like knives in your back\nBlood feeders, winged death dealers\ndescending a disguised aerial attack\nRavenous are the regal ravens\nlike opportunistic thieves picking at your bones\nPreying solely upon the weak\nraptors commanding carrion thrones\nSnakes and vultures\n...you are…\nfucking snakes and vultures\n...you are…\nFarewell dreams of liberty\nnone more enslaved\nthan those who believe they’re free\nForsaken thoughts of prosperity\nnone more defeated\nthan those obsolete\nGive way the logic of all rationality\nnone more deprived than\nthose blinded by greed\nIncarcerated within world slavery\nnone more alive\nthan we who bleed\nSnakes and vultures\n...you are…\nfucking snakes and vultures\n...you are…"
  val c = "Confined in hopeless valleys\nstricken with vast veil of shadow\nno light will reach beyond these mountains\nthere's more comfort to be found among gallows\nWe're lost within the pitch of gloom\nas night-tide piles the dead ashore\nthe breathless laugh in the face of dreams\nand the subsisting smirk midst scaling banks of gore\nDecomposing tower\nself-generating cadaverous Gate to Abaddon\nLining lungs with azure plage\nall will succumb to putrefaction\nAnd we crawl higher... over the dying\nwithout remorse, for life we're prying\nand we push forward... we march on\ninto nothing... where we belong"
  val d = "Supreme scarlet splendor\nsky-swept across astral planes\nAncient illustrated lifeforms\nare the stellar constellations within our veins\nBehold galaxies of collapsed matter\nthe great vacuum of buried truth\nWitnessing the former shades shatter\nwhile waiting for the breaking of misinformed youth\nOrbiting the ego sun\nbarren oasis of the soul\nStar-fall; the downward one\ngenerating outright black hole\nWhirlwinds fuel the illusions of importance\nsandstorms guiding back the blind\nDying are opportunities for self-contortion\nhorses high will ride enshrined\nTemptations are the fires that burn the hands\nwhile seeking fountains to quench one's thirst\nAnd yet we bathe in the lava rivers of Vulcan\nin hopes that a lost god will grant us rebirth\nExpand the mind well beyond Yesteryear\nBreathe every breath until the very last\nBronze are the caskets of all regret and fear\nFor all we are is blood, sand, ash"
  val e = "Circular tomb\nthe mind, body & soul\nFramed in flash\nelevating beyond control\nSuspended in animation\ntimeless, motionless walls\nCelestial divination\nechoing throughout our vacant halls\nWe are of these stars\nlong dead before we're seen\nEnslaved before our start\nbound in our illusions & dreams\nMadness overtake my mind\nlet beat my heart to the cadence of the wind\nFor what else is there left to find\nwhen we are born imprisoned from within?"
  val f = "Oh great mirror, ye who sees through me\nParallel dimension, nebula of symmetry\nShatter my reflection, distort the memories\nOh great mirror, ye who sees through me\nLingering behind the pane\nreplicating the here & now\nEmpathy beyond the sane\nvanishing the optic shroud\nDeeper down into the maze\nwaiting there the archetype\nEntranced in paradigm gaze\ndimmer becomes the inner light\nOh great mirror, ye who sees through me\nParallel dimension, nebula of symmetry\nShatter my reflection, distort the memories\nOh great mirror, ye who sees through me\nFading complexion\nnegating direction\nquestioning recollection\ntelepathic projection\nOh great mirror, ye who sees through me\nParallel dimension, nebula of symmetry\nShatter my reflection, distort the memories\nOh great mirror, ye who sees through me\nDiagnostic dissection\npsychiatric objection\nschizophrenic subjection\nstigmatic infection\n...ye who sees through me..."
  val g = "Return to Earth\nFaint and dark illuminating light\nTo grant rebirth\nUnder somber shade of starless night\nSweeping darkness surge\nReveal all within what you hide\nBlood moon converge, reel me in along with your tide\nResonating first breath\nLike hungered wolves howling into the hollow\nGenerate un-death\nEscape the womb and blindly follow\nRevolution is the flame\nAnswered prayers unto Apollo\nTread against the grain\nYour light is what the night will swallow\nPrevail through sacrifice\nAnd stand before the all seeing eyes\nFlawless flame we ignite\nBeyond bleakest pitch, transcendence burning bright"
  val h = "Darkness cloak us all\nWild cosmic onyx gorge\nWhere Orion once stood tall\nAnd sagittarian arrows soar\nTwilight engulf us all\nSupreme existence ignored\nUnited we shall fall\nIndependence unexplored\nLost, here in time\nPerpetually still\nWe are indoctrinated blind\nIn opposition to our will\nFading is the light that never shines\nAiding manipulation against our minds\n"
  val i = "Here below the great watching eyes\nDeception encases the illusion of our lives\nThy will be done, without the son\nWhere are we to seek meaning in your truth\nWhen only fib, fable and fiction is absolute\nDeny his name, there are no flames\nConstitutionally enslaved\nWe would surely drown if it wasn't for the waves\nLook to the sky, open your eyes\nAt what point will we try to break away\nAnd turn back from the paths that they have paved\nWe have to see, we are not free"
  val j = "Below the tide we strain to breathe\nimprisoned selfish suffocating souls\nsalvation screams from high above the trees\nwhile our beating hearts beg and plead to fold\npaling light falls behind approaching clouds\nhope flutters like ashes in the wind\nso blind we've become to the burial shroud\ncautions unheard silently shriek from within\nTime is lost and we bear our scars\nwithout rise we are fearful of the fall\ndarkness has come to blanket the stars\nand even mountains vanish behind the squall\nbroken hands exhume unspoiled graves\ndigging deeper for the dust below the dirt\nhere you'll find only bones of once a slave\nridden with regrets they are unable to revert\nFaded flesh slumbering in the tomb\nan indication of our inevitable doom\nechoing voices from below the hollow\ncalling us...calling us to follow"
  val k = "Time of light is falling\nDark of night is drawing near\nTranscendental voices calling\nWhispering horror and fear\nMarching forward all alone\nWithout vision I can see\nInto the depths of the unknown\nAre the secrets that will set you free\nDistant are the stars that shine\nNot only those within our sight\nBut soaring beyond our highest mind\nInternally burning even more bright\nLevitating into the sky\nAtmospherical breach\nBreathing where no air lies\nTranscending out beyond our reach\nHollow is the heart\nThat beats within the earth\nDeath of winter starts\nAnd Walpurgis brings rebirth\nAries in the moon\nSign of the horned child\nSprint, for death will strike soon\nWhisking broad, winged and wild"

  val chain: Seq[List[String]] = SongLyricsMarkovChainGenerator.generate(List(a, b, c, d, e, f, g, h, i, j, k).mkString("\n"), 3, 15)

  val printReady = chain.map(_.mkString(" ")).mkString("\n")
  println(printReady)
}
